export const vGamesTypes = {
  FETCH_GAMES: "FETCH_GAMES",
  FETCH_GAMES_SUCCESS: "FETCH_GAMES_SUCCESS",
  FETCH_GAMES_FAILED: "FETCH_GAMES_FAILED",
  FETCH_BY_NAME: "FETCH_BY_NAME",
  DELETE_VIDEOGAME: "DELETE_VIDEOGAME",
  DELETE_VIDEOGAME_SUCCESS: "DELETE_VIDEOGAME_SUCCESS",
  CHANGE_PAGE: "CHANGE_PAGE",
  RESET_GAMES: "RESET_GAMES",
};

export const genresTypes = {
  FETCH_GENRES: "FETCH_GENRES",
  FETCH_GENRES_SUCCESS: "FETCH_GENRES_SUCCESS",
};

export const detailTypes = {
  FETCH_DETAIL: "FETCH_DETAIL",
  FETCH_DETAIL_SUCCESS: "FETCH_DETAIL_SUCCESS",
  FETCH_DETAIL_FAILED: "FETCH_DETAIL_FAILED",
  CLEAR_DETAIL: "CLEAR_DETAIL",
};

export const filtersTypes = {
  FILTER_BY_GENRE: "FILTER_BY_GENRE",
  FILTER_BY_ORIGIN: "FILTER_BY_ORIGIN",
  FILTER_BY_RATING: "FILTER_BY_RATING",
  FILTER_BY_NAME: "FILTER_BY_NAME",
};

export const modalTypes = {
  SHOW_MODAL: "SHOW_MODAL",
  HIDDE_MODAL: "HIDDE_MODAL",
};
